feat: list item filter chip component
vuestorefront/sfui2 pull request #527
Opened 2023-02-08 11:09 UTC by justyna-13

# Related issue

Closes #

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] Self code-reviewed
- [ ] Changes documented
- [ ] Semantic HTML
- [ ] SSR-friendly
- [ ] Caching friendly
- [ ] a11y for WCAG 2.0 AA
- [ ] examples created
- [ ] created cypress tests

2023-02-09 09:48 UTC, aniamusial commented on apps/docs/components/.vuepress/components/componentsDescription.json
> +    "VsfListItemFilterChip": "A ListItemFilterChip component is a Chip component adapted to appear in lists.",
suggestion: new approach for docs description was introduced here: https://github.com/vuestorefront/sfui2/pull/507 Can you please adjust docs changes to it? :)

2023-02-09 10:05 UTC, aniamusial requested changes
good job, just the docs change and some smaller suggestions :)

2023-02-09 10:05 UTC, aniamusial commented on packages/sfui/frameworks/vue/components/VsfChip/VsfChip.vue
> +    :class="`vsf-chip--size-${size}`"
you can merge it into one, more or less like this: `:class=['vsf-chip', `vsf-chip--size-${size}`]`

2023-02-09 12:58 UTC, AdamPawlinski approved these changes

2023-02-14 09:02 UTC, aniamusial approved these changes

2023-02-15 06:28 UTC, merged